routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::delete('/requests', "RequestController@clear")->name('requests.clear');

Route::resources([
	'categories' => 'CategoryController',
	'assets' => 'AssetController',
	'requests' => 'RequestController',
	'tickets' => 'TicketController'

]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = ['name'];

    public function Assets()
    {
    	return $this->hasMany('App\Asset');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Asset;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $this->authorize('viewAny', Category::class);
        // $categories = Category::all()->sortBy('name');
        // return view('categories.index')->with('categories', $categories);

        if (Auth::check()) {
            $categories = Category::all();
            foreach ($categories as $category) {
                $assets = Asset::where('category_id', $category->id)->get();
                $availableAssets = Asset::where('status_id', 1)->where('category_id', $category->id)->get();
                $category->available_stocks = count($availableAssets);
                $category->total_stocks = count($assets);
            }
            return view('categories.index')
                ->with('categories', $categories);
                
        } else {
            return abort(403, 'This action is unauthorized.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Category::class);
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    
        $this->authorize('create', Category::class);
        $validatedData = $request->validate([
            'name' => 'required|unique:categories,name'
        ]);

        $category = new Category($validatedData);
        $category->save();
        return redirect(route('categories.index'))->with('message', "Category {$category->name} is added successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        // $this->authorize('view', $category);
        // return view('categories.show')
        //     ->with('category', $category)
        //     ->with('assets', $assets);

        if (Auth::check()) {
            $assets = Asset::where('category_id', $category->id)->get();
            $availableAssets = Asset::where('status_id', 1)->where('category_id', $category->id)->get();
            $category->available_stocks = count($availableAssets);
            $category->total_stocks = count($assets);
            $category->save();
            return view('categories.show')
                ->with('category', $category)
                ->with('assets', $assets);
        } else {
            return abort(403, 'This action is unauthorized.');
        }
;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
        return view('categories.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
        $validatedData = $request->validate([
            'name' => 'required|unique:categories,name'
        ]);
        $category->update($validatedData);
        $category->save();

        return redirect( route('categories.show', $category->id))->with('message', "Category is updated successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);
        $category->delete();
        return redirect(route('categories.index'))
        ->with('message', "Category {$category->name} has been deleted")
        ->with('alert', 'warning');
    }
}

resources/views/categories/create.blade.php
{{-- @extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">
					Create New Category
				</h1>
			</div>
		</div>
		
		@if ($errors->any())
		    <div class="alert alert-danger">
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </div>
		@endif

		start form section
		<div class="row">
			<div class="col-12 col-sm-6 mx-auto">
				<form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
					@csrf
					
					<label for="name">Category name:</label>
					<input type="text" name="name" id="name" class="form-control form-control-sm">
					<button class="btn btn-sm btn-primary mt-1">Create Category</button>
				</form>
			</div>
		</div>
		{{-- end form section --}}
	{{-- </div>
@endsection() --}} 

@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-10 col-lg-9 col-md-8 ml-auto p-4">
            {{-- header --}}
            <div class="row">
                <div class="col-12 text-center">
                    <h1 class="text-center lead display-4">
                        Create Item
                    </h1>
                </div>
            </div>
            {{-- end header --}}

            {{-- Create item --}}
            <div class="row mt-5">
                <div class="col-12 col-md-6 mx-auto">
                    {{-- form --}}
                    <form action="{{ route('categories.store') }}" method="post">
                        @csrf
                        <label for="name">Category name:</label>
                        <input type="text" name="name" id="name"
                            class="
                                form-control
                                form-control-sm
                                @error('name')
									is-invalid
								@enderror
                            "
                        required>
                        @error('name')
                            <small class="d-block invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </small>
                        @enderror
                        <button class="btn btn-md btn-primary mt-2">
                            Create Item
                        </button>
                    </form>
                    {{-- end form --}}
                </div>

            </div>
            {{-- end Create item --}}
        </div>
    </div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center">Edit Category</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-12 col-md-6 mx-auto">
				{{-- start form --}}
				<form action="{{ route('categories.update', $category->id) }}" method="post">
					@csrf
					@method('PUT')
					<label for="name">Category name:</label>
					<input 
						type="text" 
						name="name" 
						id="name" 
						class="form-control 
									@error('name')
										is-invalid
									@enderror
									form-control-sm"
						value="{{ $category->name }}" autofocus>
						@error('name')
							<small class="d-block invalid-feedback">
								<strong>{{ $message }}</strong>
							</small> 
						@enderror
					<button class="btn btn-sm btn-warning mt-1">Edit</button>
				</form>
				{{-- end form --}}
			</div>
		</div>
	</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
	{{-- alert message --}}
	@includeWhen(Session::has('message'), 'partials.alert')
	<div class="card-header mx-4">
			<h1>Categories</h1>
		</div>
	<div class="row mx-4">
		{{-- card start --}}
		@foreach($categories as $category)
			<div class="col-12 col-sm-6 col-md-4 col-lg-3 ">
				
				@include('categories.partials.card')

			</div>
		@endforeach
	</div>

@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    {{-- alert message --}}
    @includeWhen(Session::has('message'), 'partials.alert')
    {{-- end of alert message --}}

    <div class="row">
        {{-- item details and create item unit --}}
        <div class="col-12 col-md-4 col-lg-3 mb-5 bg-light">
            <div class="bottom-border pb-3">
                <h1 class="display-lg-4">{{$category->name}}</h1>
                <p class="lead mb-2">Stocks Available: {{$category->available_stocks}} / {{$category->total_stocks}}</p>
                @can('isAdmin')
                    <a href="{{route('categories.edit', $category->id)}}" class=" btn btn-sm btn-warning"><i class="far fa-edit fa-lg"></i> Edit</a>
                    <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                    	@csrf
                    	@method('DELETE')
                    	<button class="btn btn-danger btn-sm">Delete</button>
                    </form>
                @endcan
                <hr>
            </div>
            
            @can('isAdmin')
                @include('categories.partials.create-asset')
            @endcan
        </div>
		
        {{-- end of category details and create category unit --}}
        <div class="col-12 col-md-8 col-lg-9">
            <div class="row">
                {{-- no units alert --}}
                @if(count($assets) === 0)
                    <div class="col-8 mt-4 mx-auto">
                        @include('partials.no-entry-alert', [
                            'title' => 'assets'
                        ])
                    </div>
                @endif
                {{-- end no units alert --}}

                {{-- units section --}}
                @foreach($assets as $asset)
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-2">
                    {{-- unit card --}}
                    <div class="card">

                        <img src="{{ $asset->image }}" alt="" class="card-img-top">

                        <div class="card-body">
                        	<h3 class="card-title">
                                {{ $asset->name }}
                            </h3>
                            <p class="card-title">
                               Control Code: {{ $asset->control_code }}
                            </p>
                            
                            <h5>Category:
                                <span class="badge badge-primary ">{{$asset->category->name}}</span>
                            </h5>
                            <h5 class="card-text mb-0">
                                Status: <span
                                            class="badge
                                                @if($asset->status_id === 1)
                                                    badge-success
                                                @elseif($asset->status_id === 2)
                                                    badge-danger
                                                @elseif($asset->status_id === 3)
                                                    badge-warning
                                                @endif
                                            ">{{ $asset->asset_status->name }}</span>
                            </h5>
                        </div>
                        <div class="card-footer bg-secondary text-white">

                            @include('assets.partials.request-btn')
                            <a href="{{ route('assets.show', $asset->id) }}" class="btn btn-sm btn-info w-100 mb-1">View</a>
                            @can('isAdmin')
                                @include('assets.partials.edit-btn')
                                @include('assets.partials.delete-form')
                            @endcan
                        </div>
                    </div>
                    {{-- unit card end --}}
                </div>
                @endforeach
                {{-- units section end --}}
            </div>
        </div>


    </div>
</div>
@endsection