routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::delete('/requests', "RequestController@clear")->name('requests.clear');

Route::resources([
	'categories' => 'CategoryController',
	'assets' => 'AssetController',
	'requests' => 'RequestController',
	'tickets' => 'TicketController'

]);

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @can('isAdmin')
                        {{-- start admin dropdown --}}
                        <li class="nav-item dropdown">
                            <a id="adminDropdown" href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown">Admin</a>
                        <div class="dropdown-menu">

                            {{-- add category --}}
                            <a href="{{ route('categories.create') }}" class="dropdown-item">Add Category</a>

                            {{-- add product --}}
                            <a href="{{ route('assets.create') }}" class="dropdown-item">Add Asset</a>
                        </div>
                        </li>
                        @endcan
                        {{-- end admin dropdown --}}
                       
                            {{-- categories --}}
                            @auth
                             <li class="{{ Route::CurrentRouteNamed('categories.index') ? "active" : "" }}">
                                <a href="{{ route('categories.index') }}" class="nav-link">Categories</a>
                            </li>
                            
                        {{-- assets --}}
                        <li class="{{ Route::CurrentRouteNamed('assets.index') ? "active" : "" }}">
                            <a href="{{ route('assets.index') }}" class="nav-link">Assets</a>
                        </li>

                        <li class="{{ Route::CurrentRouteNamed('tickets.index') ? "active" : "" }}">
                            <a href="{{ route('tickets.index') }}" class="nav-link">Tickets</a>
                        </li>
                        @endauth

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        @cannot('isAdmin')
                        {{-- requests start --}}
                        @auth
                        <li class="nav-item {{ Route::CurrentRouteNamed('requests.index') ? "active" : "" }}">
                            <a href="{{ route('requests.index') }}" class="nav-link">
                                Requests
                                <span class="badge badge-primary">{{ Session::has('request') ? count(Session::get('request')) : 0 }}</span>
                            </a>
                        </li>
                        @endauth
                        @endcannot

                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>